//
//  Size.swift
//  VishalCATAAS
//
//  Created by Vishal Polepalli on 6/30/22.
//

import Foundation

import SwiftUI

let MARGIN_SCREEN = CGFloat(20)
let MARGIN_SCREEN_LEFT_RIGHT = CGFloat(20)
let MARGIN_SCREEN_TOP_BOTTOM = CGFloat(32)
let MARGIN_HEADER_STACK_BOTTOM = CGFloat(40)
let SIZE_HEIGHT_TEXTFIELD_PRECEDING_ICON = CGFloat(20)
let SIZE_FONT_DEFAULT = CGFloat(17)
let SIZE_FONT_SMALL = CGFloat(12)
let SIZE_PADDING_TOP_BUTTON_STACK = CGFloat(32)
let SIZE_PADDING_XXXL = CGFloat(80)
let SIZE_PADDING_XL = CGFloat(40)
let SIZE_PADDING_LARGE = CGFloat(32)
let SIZE_PADDING_NORMAL = CGFloat(16)
let SIZE_PADDING_SMALL = CGFloat(8)
let SIZE_PADDING_XS = CGFloat(6)
let SIZE_PADDING_XXS = CGFloat(4)
let SIZE_PADDING_TOOLTIP = CGFloat(24)
let CORNER_RADIUS_TEXT_FIELD = CGFloat(8)
let STROKE_WIDTH = CGFloat(1)
let SIZE_WIDTH_MAX_HERO_IMAGE = CGFloat(450)
let SIZE_PERCENT_ICON_FLUSH = CGFloat(3.4)
